### ISSUE TITLE
SVG validation rules bugs

### ISSUE THREAD

**Issue by aVandalInShorts** [DeuxHuitHuit/image_upload#28]
To be able to have a SVG, I have to clear the regex of the validation rules. When I click on "image+svg", it doesn't do anything. So I have to leave it empty.

If I go back to the blueprint of the section, it automaticly adds to normal image validation rule to the empty validation rule in the fields. So when I save the blueprints, it saves the validation rules. Therefore, if I go save the entry, all the SVG images are not valid anymore.

**Comment by animaux** [comment]
Confirmed.

**Comment by nitriques** [comment]
Fixed in 640a3e2 and released. Thanks!
